### ISSUE TITLE
Publish demo 

### ISSUE THREAD

**Issue by wayne-o** [wayne-o/sonatribe-ui#3]
We can publish the UI code to gh-pages  - it's free and fast and super easy:

https://developer.mozilla.org/en-US/Apps/Build/Modern_web_app_architecture/Publishing_your_app

**Comment by chrismou** [comment]
That's actually a really goo idea - get a demo up and running and worry about faffing around with hosting later

**Comment by wayne-o** [comment]
I know! LOL - I've added a task to deploy the API to Heroku as that is
ridiculously easy too: https://github.com/wayne-o/sonatribe-api/issues/1

On Tue, Jan 27, 2015 at 10:41 AM, Chris Chrisostomou <
notifications@github.com> wrote:

> That's actually a really goo idea - get a demo up and running and worry
> about faffing around with hosting later
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wayne-o/sonatribe-ui/issues/3#issuecomment-71624764>.
>



-- 
*--------------------*

*w://*

*t: 07508 215 459*

*--------------------*

**Comment by wayne-o** [comment]
If anyone fancies tackling these yet! @thestumonkey @chrismou  ;)

**Comment by wayne-o** [comment]
tried... failed!

http://wayne-o.github.io/sonatribe-ui/

Looking into it now

On Tue, Jan 27, 2015 at 11:12 AM, Wayne Douglas <wayne@prjatk.com> wrote:

> I know! LOL - I've added a task to deploy the API to Heroku as that is
> ridiculously easy too: https://github.com/wayne-o/sonatribe-api/issues/1
>
> On Tue, Jan 27, 2015 at 10:41 AM, Chris Chrisostomou <
> notifications@github.com> wrote:
>
>> That's actually a really goo idea - get a demo up and running and worry
>> about faffing around with hosting later
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/wayne-o/sonatribe-ui/issues/3#issuecomment-71624764>.
>>
>
>
>
> --
> *--------------------*
>
> *w://*
>
> *t: 07508 215 459*
>
> *--------------------*
>
>


-- 
*--------------------*

*w://*

*t: 07508 215 459*

*--------------------*

**Comment by wayne-o** [comment]
It works!!

http://wayne-o.github.io/sonatribe-ui/

@chrismou

On Tue, Jan 27, 2015 at 1:28 PM, Wayne Douglas <wayne@prjatk.com> wrote:

> tried... failed!
>
> http://wayne-o.github.io/sonatribe-ui/
>
> Looking into it now
>
> On Tue, Jan 27, 2015 at 11:12 AM, Wayne Douglas <wayne@prjatk.com> wrote:
>
>> I know! LOL - I've added a task to deploy the API to Heroku as that is
>> ridiculously easy too: https://github.com/wayne-o/sonatribe-api/issues/1
>>
>> On Tue, Jan 27, 2015 at 10:41 AM, Chris Chrisostomou <
>> notifications@github.com> wrote:
>>
>>> That's actually a really goo idea - get a demo up and running and worry
>>> about faffing around with hosting later
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/wayne-o/sonatribe-ui/issues/3#issuecomment-71624764>
>>> .
>>>
>>
>>
>>
>> --
>> *--------------------*
>>
>> *w://*
>>
>> *t: 07508 215 459*
>>
>> *--------------------*
>>
>>
>
>
> --
> *--------------------*
>
> *w://*
>
> *t: 07508 215 459*
>
> *--------------------*
>
>


-- 
*--------------------*

*w://*

*t: 07508 215 459*

*--------------------*

**Comment by wayne-o** [comment]
need to configure the custom URL now and also the fb auth stuff in the
ENV/Production config.js

On Tue, Jan 27, 2015 at 2:18 PM, Wayne Douglas <wayne@prjatk.com> wrote:

> It works!!
>
> http://wayne-o.github.io/sonatribe-ui/
>
> @chrismou
>
> On Tue, Jan 27, 2015 at 1:28 PM, Wayne Douglas <wayne@prjatk.com> wrote:
>
>> tried... failed!
>>
>> http://wayne-o.github.io/sonatribe-ui/
>>
>> Looking into it now
>>
>> On Tue, Jan 27, 2015 at 11:12 AM, Wayne Douglas <wayne@prjatk.com> wrote:
>>
>>> I know! LOL - I've added a task to deploy the API to Heroku as that is
>>> ridiculously easy too: https://github.com/wayne-o/sonatribe-api/issues/1
>>>
>>> On Tue, Jan 27, 2015 at 10:41 AM, Chris Chrisostomou <
>>> notifications@github.com> wrote:
>>>
>>>> That's actually a really goo idea - get a demo up and running and worry
>>>> about faffing around with hosting later
>>>>
>>>> —
>>>> Reply to this email directly or view it on GitHub
>>>> <https://github.com/wayne-o/sonatribe-ui/issues/3#issuecomment-71624764>
>>>> .
>>>>
>>>
>>>
>>>
>>> --
>>> *--------------------*
>>>
>>> *w://*
>>>
>>> *t: 07508 215 459*
>>>
>>> *--------------------*
>>>
>>>
>>
>>
>> --
>> *--------------------*
>>
>> *w://*
>>
>> *t: 07508 215 459*
>>
>> *--------------------*
>>
>>
>
>
> --
> *--------------------*
>
> *w://*
>
> *t: 07508 215 459*
>
> *--------------------*
>
>


-- 
*--------------------*

*w://*

*t: 07508 215 459*

*--------------------*

**Comment by chrismou** [comment]
Fuck yeah!  :-D

Is it based off the live repo?  So does it essentially update on every push?

**Comment by wayne-o** [comment]
Just push to the gh-pages branch...

On Tue, Jan 27, 2015 at 2:46 PM, Chris Chrisostomou <
notifications@github.com> wrote:

> Fuck yeah! :-D
>
> Is it based off the live repo? So does it essentially update on every
> push?
>
> On 27 January 2015 at 14:35, wayne-o <notifications@github.com> wrote:
>
> > need to configure the custom URL now and also the fb auth stuff in the
> > ENV/Production config.js
> >
> > On Tue, Jan 27, 2015 at 2:18 PM, Wayne Douglas <wayne@prjatk.com>
> wrote:
> >
> > > It works!!
> > >
> > > http://wayne-o.github.io/sonatribe-ui/
> > >
> > > @chrismou
> > >
> > > On Tue, Jan 27, 2015 at 1:28 PM, Wayne Douglas <wayne@prjatk.com>
> > wrote:
> > >
> > >> tried... failed!
> > >>
> > >> http://wayne-o.github.io/sonatribe-ui/
> > >>
> > >> Looking into it now
> > >>
> > >> On Tue, Jan 27, 2015 at 11:12 AM, Wayne Douglas <wayne@prjatk.com>
> > wrote:
> > >>
> > >>> I know! LOL - I've added a task to deploy the API to Heroku as that
> is
> > >>> ridiculously easy too:
> > https://github.com/wayne-o/sonatribe-api/issues/1
> > >>>
> > >>> On Tue, Jan 27, 2015 at 10:41 AM, Chris Chrisostomou <
> > >>> notifications@github.com> wrote:
> > >>>
> > >>>> That's actually a really goo idea - get a demo up and running and
> > worry
> > >>>> about faffing around with hosting later
> > >>>>
> > >>>> —
> > >>>> Reply to this email directly or view it on GitHub
> > >>>> <
> > https://github.com/wayne-o/sonatribe-ui/issues/3#issuecomment-71624764>
> > >>>> .
> > >>>>
> > >>>
> > >>>
> > >>>
> > >>> --
> > >>> *--------------------*
> > >>>
> > >>> *w://*
> > >>>
> > >>> *t: 07508 215 459*
> > >>>
> > >>> *--------------------*
> > >>>
> > >>>
> > >>
> > >>
> > >> --
> > >> *--------------------*
> > >>
> > >> *w://*
> > >>
> > >> *t: 07508 215 459*
> > >>
> > >> *--------------------*
> > >>
> > >>
> > >
> > >
> > > --
> > > *--------------------*
> > >
> > > *w://*
> > >
> > > *t: 07508 215 459*
> > >
> > > *--------------------*
> > >
> > >
> >
> >
> > --
> > *--------------------*
> >
> > *w://*
> >
> > *t: 07508 215 459*
> >
> > *--------------------*
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/wayne-o/sonatribe-ui/issues/3#issuecomment-71656925>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wayne-o/sonatribe-ui/issues/3#issuecomment-71658718>.
>



-- 
*--------------------*

*w://*

*t: 07508 215 459*

*--------------------*

**Comment by wayne-o** [comment]
fixed the URL: http://test.sonatribe.com/

Will fix the FB auth code stuff on the train.

I might have a pop at deploying the API to Heroku too unless anyone else
fancies it...


On Tue, Jan 27, 2015 at 3:02 PM, Wayne Douglas <wayne@prjatk.com> wrote:

> Just push to the gh-pages branch...
>
> On Tue, Jan 27, 2015 at 2:46 PM, Chris Chrisostomou <
> notifications@github.com> wrote:
>
>> Fuck yeah! :-D
>>
>> Is it based off the live repo? So does it essentially update on every
>> push?
>>
>> On 27 January 2015 at 14:35, wayne-o <notifications@github.com> wrote:
>>
>> > need to configure the custom URL now and also the fb auth stuff in the
>> > ENV/Production config.js
>> >
>> > On Tue, Jan 27, 2015 at 2:18 PM, Wayne Douglas <wayne@prjatk.com>
>> wrote:
>> >
>> > > It works!!
>> > >
>> > > http://wayne-o.github.io/sonatribe-ui/
>> > >
>> > > @chrismou
>> > >
>> > > On Tue, Jan 27, 2015 at 1:28 PM, Wayne Douglas <wayne@prjatk.com>
>> > wrote:
>> > >
>> > >> tried... failed!
>> > >>
>> > >> http://wayne-o.github.io/sonatribe-ui/
>> > >>
>> > >> Looking into it now
>> > >>
>> > >> On Tue, Jan 27, 2015 at 11:12 AM, Wayne Douglas <wayne@prjatk.com>
>> > wrote:
>> > >>
>> > >>> I know! LOL - I've added a task to deploy the API to Heroku as that
>> is
>> > >>> ridiculously easy too:
>> > https://github.com/wayne-o/sonatribe-api/issues/1
>> > >>>
>> > >>> On Tue, Jan 27, 2015 at 10:41 AM, Chris Chrisostomou <
>> > >>> notifications@github.com> wrote:
>> > >>>
>> > >>>> That's actually a really goo idea - get a demo up and running and
>> > worry
>> > >>>> about faffing around with hosting later
>> > >>>>
>> > >>>> —
>> > >>>> Reply to this email directly or view it on GitHub
>> > >>>> <
>> > https://github.com/wayne-o/sonatribe-ui/issues/3#issuecomment-71624764>
>>
>> > >>>> .
>> > >>>>
>> > >>>
>> > >>>
>> > >>>
>> > >>> --
>> > >>> *--------------------*
>> > >>>
>> > >>> *w://*
>> > >>>
>> > >>> *t: 07508 215 459*
>> > >>>
>> > >>> *--------------------*
>> > >>>
>> > >>>
>> > >>
>> > >>
>> > >> --
>> > >> *--------------------*
>> > >>
>> > >> *w://*
>> > >>
>> > >> *t: 07508 215 459*
>> > >>
>> > >> *--------------------*
>> > >>
>> > >>
>> > >
>> > >
>> > > --
>> > > *--------------------*
>> > >
>> > > *w://*
>> > >
>> > > *t: 07508 215 459*
>> > >
>> > > *--------------------*
>> > >
>> > >
>> >
>> >
>> > --
>> > *--------------------*
>> >
>> > *w://*
>> >
>> > *t: 07508 215 459*
>> >
>> > *--------------------*
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/wayne-o/sonatribe-ui/issues/3#issuecomment-71656925>.
>>
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/wayne-o/sonatribe-ui/issues/3#issuecomment-71658718>.
>>
>
>
>
> --
> *--------------------*
>
> *w://*
>
> *t: 07508 215 459*
>
> *--------------------*
>
>


-- 
*--------------------*

*w://*

*t: 07508 215 459*

*--------------------*

**Comment by chrismou** [comment]
What is the api? nodejs?

**Comment by wayne-o** [comment]
Yeah

https://github.com/wayne-o/sonatribe-api/issues/1

There's a "template" here https://github.com/chadn/heroku-sails - we can
likely just pull the meaningful bits (Procfile etc) and deploy from that -
you do need the heroku toolbelt installed though

I'm not stuck on Heroku - just seems the easiest amongst Node devs - I
could be wrong though - if anyone wants to investigate alternatives I am
definitely down with that



On Tue, Jan 27, 2015 at 3:38 PM, Chris Chrisostomou <
notifications@github.com> wrote:

> What is the api? nodejs?
>
> On 27 January 2015 at 15:31, wayne-o <notifications@github.com> wrote:
>
> > fixed the URL: http://test.sonatribe.com/
> >
> > Will fix the FB auth code stuff on the train.
> >
> > I might have a pop at deploying the API to Heroku too unless anyone else
> > fancies it...
> >
> >
> > On Tue, Jan 27, 2015 at 3:02 PM, Wayne Douglas <wayne@prjatk.com>
> wrote:
> >
> > > Just push to the gh-pages branch...
> > >
> > > On Tue, Jan 27, 2015 at 2:46 PM, Chris Chrisostomou <
> > > notifications@github.com> wrote:
> > >
> > >> Fuck yeah! :-D
> > >>
> > >> Is it based off the live repo? So does it essentially update on every
> > >> push?
> > >>
> > >> On 27 January 2015 at 14:35, wayne-o <notifications@github.com>
> wrote:
> > >>
> > >> > need to configure the custom URL now and also the fb auth stuff in
> > the
> > >> > ENV/Production config.js
> > >> >
> > >> > On Tue, Jan 27, 2015 at 2:18 PM, Wayne Douglas <wayne@prjatk.com>
> > >> wrote:
> > >> >
> > >> > > It works!!
> > >> > >
> > >> > > http://wayne-o.github.io/sonatribe-ui/
> > >> > >
> > >> > > @chrismou
> > >> > >
> > >> > > On Tue, Jan 27, 2015 at 1:28 PM, Wayne Douglas <wayne@prjatk.com>
>
> > >> > wrote:
> > >> > >
> > >> > >> tried... failed!
> > >> > >>
> > >> > >> http://wayne-o.github.io/sonatribe-ui/
> > >> > >>
> > >> > >> Looking into it now
> > >> > >>
> > >> > >> On Tue, Jan 27, 2015 at 11:12 AM, Wayne Douglas <
> wayne@prjatk.com>
> >
> > >> > wrote:
> > >> > >>
> > >> > >>> I know! LOL - I've added a task to deploy the API to Heroku as
> > that
> > >> is
> > >> > >>> ridiculously easy too:
> > >> > https://github.com/wayne-o/sonatribe-api/issues/1
> > >> > >>>
> > >> > >>> On Tue, Jan 27, 2015 at 10:41 AM, Chris Chrisostomou <
> > >> > >>> notifications@github.com> wrote:
> > >> > >>>
> > >> > >>>> That's actually a really goo idea - get a demo up and running
> > and
> > >> > worry
> > >> > >>>> about faffing around with hosting later
> > >> > >>>>
> > >> > >>>> —
> > >> > >>>> Reply to this email directly or view it on GitHub
> > >> > >>>> <
> > >> >
> > https://github.com/wayne-o/sonatribe-ui/issues/3#issuecomment-71624764>
> > >>
> > >> > >>>> .
> > >> > >>>>
> > >> > >>>
> > >> > >>>
> > >> > >>>
> > >> > >>> --
> > >> > >>> *--------------------*
> > >> > >>>
> > >> > >>> *w://*
> > >> > >>>
> > >> > >>> *t: 07508 215 459*
> > >> > >>>
> > >> > >>> *--------------------*
> > >> > >>>
> > >> > >>>
> > >> > >>
> > >> > >>
> > >> > >> --
> > >> > >> *--------------------*
> > >> > >>
> > >> > >> *w://*
> > >> > >>
> > >> > >> *t: 07508 215 459*
> > >> > >>
> > >> > >> *--------------------*
> > >> > >>
> > >> > >>
> > >> > >
> > >> > >
> > >> > > --
> > >> > > *--------------------*
> > >> > >
> > >> > > *w://*
> > >> > >
> > >> > > *t: 07508 215 459*
> > >> > >
> > >> > > *--------------------*
> > >> > >
> > >> > >
> > >> >
> > >> >
> > >> > --
> > >> > *--------------------*
> > >> >
> > >> > *w://*
> > >> >
> > >> > *t: 07508 215 459*
> > >> >
> > >> > *--------------------*
> > >> >
> > >> > —
> > >> > Reply to this email directly or view it on GitHub
> > >> > <
> > https://github.com/wayne-o/sonatribe-ui/issues/3#issuecomment-71656925>.
>
> > >>
> > >> >
> > >>
> > >> —
> > >> Reply to this email directly or view it on GitHub
> > >> <
> https://github.com/wayne-o/sonatribe-ui/issues/3#issuecomment-71658718>.
> >
> > >>
> > >
> > >
> > >
> > > --
> > > *--------------------*
> > >
> > > *w://*
> > >
> > > *t: 07508 215 459*
> > >
> > > *--------------------*
> > >
> > >
> >
> >
> > --
> > *--------------------*
> >
> > *w://*
> >
> > *t: 07508 215 459*
> >
> > *--------------------*
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/wayne-o/sonatribe-ui/issues/3#issuecomment-71666940>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wayne-o/sonatribe-ui/issues/3#issuecomment-71668195>.
>



-- 
*--------------------*

*w://*

*t: 07508 215 459*

*--------------------*

**Comment by wayne-o** [comment]
fixed the appid for the fb login - still not complete though as I need to
finish off the workflow to fetch the ST user. but it logs you in... how
very exciting... You can tell I'm bored @work!

On Tue, Jan 27, 2015 at 3:42 PM, Wayne Douglas <wayne@prjatk.com> wrote:

> Yeah
>
> https://github.com/wayne-o/sonatribe-api/issues/1
>
> There's a "template" here https://github.com/chadn/heroku-sails - we can
> likely just pull the meaningful bits (Procfile etc) and deploy from that -
> you do need the heroku toolbelt installed though
>
> I'm not stuck on Heroku - just seems the easiest amongst Node devs - I
> could be wrong though - if anyone wants to investigate alternatives I am
> definitely down with that
>
>
>
> On Tue, Jan 27, 2015 at 3:38 PM, Chris Chrisostomou <
> notifications@github.com> wrote:
>
>> What is the api? nodejs?
>>
>> On 27 January 2015 at 15:31, wayne-o <notifications@github.com> wrote:
>>
>> > fixed the URL: http://test.sonatribe.com/
>> >
>> > Will fix the FB auth code stuff on the train.
>> >
>> > I might have a pop at deploying the API to Heroku too unless anyone
>> else
>> > fancies it...
>> >
>> >
>> > On Tue, Jan 27, 2015 at 3:02 PM, Wayne Douglas <wayne@prjatk.com>
>> wrote:
>> >
>> > > Just push to the gh-pages branch...
>> > >
>> > > On Tue, Jan 27, 2015 at 2:46 PM, Chris Chrisostomou <
>> > > notifications@github.com> wrote:
>> > >
>> > >> Fuck yeah! :-D
>> > >>
>> > >> Is it based off the live repo? So does it essentially update on
>> every
>> > >> push?
>> > >>
>> > >> On 27 January 2015 at 14:35, wayne-o <notifications@github.com>
>> wrote:
>> > >>
>> > >> > need to configure the custom URL now and also the fb auth stuff in
>> > the
>> > >> > ENV/Production config.js
>> > >> >
>> > >> > On Tue, Jan 27, 2015 at 2:18 PM, Wayne Douglas <wayne@prjatk.com>
>> > >> wrote:
>> > >> >
>> > >> > > It works!!
>> > >> > >
>> > >> > > http://wayne-o.github.io/sonatribe-ui/
>> > >> > >
>> > >> > > @chrismou
>> > >> > >
>> > >> > > On Tue, Jan 27, 2015 at 1:28 PM, Wayne Douglas <wayne@prjatk.com>
>>
>> > >> > wrote:
>> > >> > >
>> > >> > >> tried... failed!
>> > >> > >>
>> > >> > >> http://wayne-o.github.io/sonatribe-ui/
>> > >> > >>
>> > >> > >> Looking into it now
>> > >> > >>
>> > >> > >> On Tue, Jan 27, 2015 at 11:12 AM, Wayne Douglas <
>> wayne@prjatk.com>
>> >
>> > >> > wrote:
>> > >> > >>
>> > >> > >>> I know! LOL - I've added a task to deploy the API to Heroku as
>> > that
>> > >> is
>> > >> > >>> ridiculously easy too:
>> > >> > https://github.com/wayne-o/sonatribe-api/issues/1
>> > >> > >>>
>> > >> > >>> On Tue, Jan 27, 2015 at 10:41 AM, Chris Chrisostomou <
>> > >> > >>> notifications@github.com> wrote:
>> > >> > >>>
>> > >> > >>>> That's actually a really goo idea - get a demo up and running
>> > and
>> > >> > worry
>> > >> > >>>> about faffing around with hosting later
>> > >> > >>>>
>> > >> > >>>> —
>> > >> > >>>> Reply to this email directly or view it on GitHub
>> > >> > >>>> <
>> > >> >
>> > https://github.com/wayne-o/sonatribe-ui/issues/3#issuecomment-71624764>
>>
>> > >>
>> > >> > >>>> .
>> > >> > >>>>
>> > >> > >>>
>> > >> > >>>
>> > >> > >>>
>> > >> > >>> --
>> > >> > >>> *--------------------*
>> > >> > >>>
>> > >> > >>> *w://*
>> > >> > >>>
>> > >> > >>> *t: 07508 215 459*
>> > >> > >>>
>> > >> > >>> *--------------------*
>> > >> > >>>
>> > >> > >>>
>> > >> > >>
>> > >> > >>
>> > >> > >> --
>> > >> > >> *--------------------*
>> > >> > >>
>> > >> > >> *w://*
>> > >> > >>
>> > >> > >> *t: 07508 215 459*
>> > >> > >>
>> > >> > >> *--------------------*
>> > >> > >>
>> > >> > >>
>> > >> > >
>> > >> > >
>> > >> > > --
>> > >> > > *--------------------*
>> > >> > >
>> > >> > > *w://*
>> > >> > >
>> > >> > > *t: 07508 215 459*
>> > >> > >
>> > >> > > *--------------------*
>> > >> > >
>> > >> > >
>> > >> >
>> > >> >
>> > >> > --
>> > >> > *--------------------*
>> > >> >
>> > >> > *w://*
>> > >> >
>> > >> > *t: 07508 215 459*
>> > >> >
>> > >> > *--------------------*
>> > >> >
>> > >> > —
>> > >> > Reply to this email directly or view it on GitHub
>> > >> > <
>> > https://github.com/wayne-o/sonatribe-ui/issues/3#issuecomment-71656925>.
>>
>> > >>
>> > >> >
>> > >>
>> > >> —
>> > >> Reply to this email directly or view it on GitHub
>> > >> <
>> https://github.com/wayne-o/sonatribe-ui/issues/3#issuecomment-71658718>.
>> >
>> > >>
>> > >
>> > >
>> > >
>> > > --
>> > > *--------------------*
>> > >
>> > > *w://*
>> > >
>> > > *t: 07508 215 459*
>> > >
>> > > *--------------------*
>> > >
>> > >
>> >
>> >
>> > --
>> > *--------------------*
>> >
>> > *w://*
>> >
>> > *t: 07508 215 459*
>> >
>> > *--------------------*
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/wayne-o/sonatribe-ui/issues/3#issuecomment-71666940>.
>>
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/wayne-o/sonatribe-ui/issues/3#issuecomment-71668195>.
>>
>
>
>
> --
> *--------------------*
>
> *w://*
>
> *t: 07508 215 459*
>
> *--------------------*
>
>


-- 
*--------------------*

*w://*

*t: 07508 215 459*

*--------------------*

**Comment by chrismou** [comment]
I'm going to upgrade the lappy to yosemite, then I'll have a crack at deploying. Looks pretty simple

**Comment by wayne-o** [comment]
You're ON FIRE today!

On Wed, Jan 28, 2015 at 3:09 PM, Chris Chrisostomou <
notifications@github.com> wrote:

> Closed #3 <https://github.com/wayne-o/sonatribe-ui/issues/3>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wayne-o/sonatribe-ui/issues/3#event-226127471>.
>



-- 
*--------------------*

*w://*

*t: 07508 215 459*

*--------------------*
